#ifndef DVAEXAMPLEALGO1_GLOBAL_H
#define DVAEXAMPLEALGO1_GLOBAL_H

#include <QtCore/qglobal.h>

# define DVAEXAMPLEALGO1_EXPORT Q_DECL_EXPORT
//#ifdef DVAEXAMPLEALGO1_LIB
//# define DVAEXAMPLEALGO1_EXPORT Q_DECL_EXPORT
//#else
//# define DVAEXAMPLEALGO1_EXPORT Q_DECL_IMPORT
//#endif

#endif // DVAEXAMPLEALGO1_GLOBAL_H
