#ifndef DVAFOURPANEVIEW_GLOBAL_H
#define DVAFOURPANEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#define DVAFOURPANEVIEW_EXPORT Q_DECL_EXPORT

//#ifdef DVAFOURPANEVIEW_LIB
//# define DVAFOURPANEVIEW_EXPORT Q_DECL_EXPORT
//#else
//# define DVAFOURPANEVIEW_EXPORT Q_DECL_IMPORT
//#endif

#endif // DVAFOURPANEVIEW_GLOBAL_H
