#ifndef HELLOLIBRARY_GLOBAL_H
#define HELLOLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HELLOLIBRARY_LIB
# define HELLOLIBRARY_EXPORT Q_DECL_EXPORT
#else
# define HELLOLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // HELLOLIBRARY_GLOBAL_H
